//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP.NETMVCfirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KitaplarSet
    {
        public int KitapNo { get; set; }
        public string KitapAdi { get; set; }
        public string YazarAdi { get; set; }
        public string Yayınevi { get; set; }
        public string KitapTür { get; set; }
        public int BasimYili { get; set; }
        public int Fiyat { get; set; }
    }
}
