//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP.NETMVCfirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KullanıcılarSet
    {
        public int KNo { get; set; }
        public string AdSoyad { get; set; }
        public string Sifre { get; set; }
        public int Telefon { get; set; }
    }
}
