//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP.NETMVCfirst.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ElektroniklerSet> ElektroniklerSets { get; set; }
        public virtual DbSet<KitaplarSet> KitaplarSets { get; set; }
        public virtual DbSet<MüziklerSet> MüziklerSet { get; set; }
        public virtual DbSet<KullanıcılarSet> KullanıcılarSet { get; set; }
    }
}
