//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP.NETMVCfirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MüziklerSet
    {
        public int MüzikNo { get; set; }
        public string SanatciAdi { get; set; }
        public string SarkiAdi { get; set; }
        public string MüzikTür { get; set; }
        public string AlbümTür { get; set; }
        public decimal Fiyat { get; set; }
    }
}
